# Generated by Django 4.1.3 on 2023-03-18 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveproapp', '0004_rename_message_contact_tb_cn_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_tb',
            new_name='contact_cn_tb',
        ),
    ]
