# Generated by Django 4.1.3 on 2023-03-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveproapp', '0006_contact_tb_delete_contact_cn_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Userimage/')),
            ],
        ),
    ]
